const BAD_REQUEST_STATUS_CODE = 400;

const NOT_FOUND_STATUS_CODE = 404;

const INTERVAL_SERVER_ERROR_STATUS_CODE = 500;

const NOT_FOUND_AUTH_STATUS = 401;

const FORBIDDEN_ERROR = 403;

const ERROR_CONFLICT = 409;

module.exports = {
  BAD_REQUEST_STATUS_CODE,
  NOT_FOUND_STATUS_CODE,
  INTERVAL_SERVER_ERROR_STATUS_CODE,
  NOT_FOUND_AUTH_STATUS,
  FORBIDDEN_ERROR,
  ERROR_CONFLICT,
};
